
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: green502

mybatis:
  type-aliases-package: com.green.board7
  mapper-locations: mapper/**/*.xml